#  TTGS2 Kontum

services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: visit_registrations
      MARIADB_USER: visit_app
      MARIADB_PASSWORD: visit_app
      MARIADB_ROOT_PASSWORD: visit_app_root
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+asyncmy://visit_app:visit_app@db:3306/visit_registrations
      SECRET_KEY: change-me-before-production
      SESSION_SAME_SITE: lax
      # SESSION_HTTPS_ONLY: false  # bỏ comment nếu test qua http
      SESSION_HTTPS_ONLY: "true"
      ALLOWED_ORIGINS: https://dangkythamgap-traitamgiamso2.hw.io.vn https://h5.zdn.vn
    expose:
      - "8000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3002:80"

volumes:
  dbdata: {}
